/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;

import java.time.Duration;

import org.example.pages.CheckboxPage;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;

class AppTest {
  WebDriver browser;

  private boolean isCI() {
    var gh = System.getenv("GITHUB_ACTIONS");
    return gh != null && gh.equals("true");
  }

  @BeforeEach
  void beforeEach() {
    var options = new FirefoxOptions();
    options.addArguments("--safe-mode");

    if (isCI()) {
      options.addArguments("--headless");
    }

    options.setCapability("webSocketUrl", true);
    browser = new FirefoxDriver(options);
    browser.manage().timeouts().implicitlyWait(Duration.ofSeconds(10));
    browser.manage().window().setSize(new Dimension(1920, 1080));
  }

  @Test
  void googleTest() throws InterruptedException {
    browser.get("https://demoqa.com/checkbox");

    var checkboxPage = CheckboxPage.init(browser);
    checkboxPage.expandPath("Home.Documents.WorkSpace");
    checkboxPage.checkNode("Home.Documents.WorkSpace.React");
    checkboxPage.checkNode("Home.Documents.WorkSpace.Angular");
    checkboxPage.validateSelectedItems(new String[] { "react", "angular" });
  }

  @AfterEach
  void afterEach() {
    browser.close();
  }
}
